### ISSUE TITLE
Weird Characters in name turn the names in the logs to numbers

### ISSUE THREAD

**Issue by Yogpod** [BadgerCode/tttdamagelogs#23] opened 2020-12-30 16:45 UTC
![image](https://user-images.githubusercontent.com/22012249/103368000-52789880-4a7b-11eb-9663-1a6392752580.png)
![image](https://user-images.githubusercontent.com/22012249/103368007-586e7980-4a7b-11eb-9473-510d0407108b.png)

**Comment by BadgerCode** [comment] 2020-12-30 18:48
Hey. Thanks for raising this!

Could you add the name you used to this issue?
This might be fixed by #22 , or it might need a similar fix to a different query.

**Comment by Yogpod** [comment] 2020-12-30 18:57
Yogpod⁧⁧what

**Comment by Yogpod** [comment] 2020-12-30 18:57
characters are in that text between what and my name

**Comment by BadgerCode** [comment] 2020-12-30 18:59
Cheers!

**Comment by BadgerCode** [comment] 2021-01-02 18:59
I don't seem to be able to replicate this with `v3.3.2` of the addon.
I used using SQLite (the default option) to store the old logs.

![preview](https://i.imgur.com/3yHOu6g.png)
![preview](https://i.imgur.com/FHUTOU0.png)



Are you using SQLite (default option; built into Garry's Mod) or MySQL for your old logs?
And could you tell me what operating system are you playing on?

**Comment by Yogpod** [comment] 2021-01-02 19:19
SQLite, playing on windows, server is linux64, client is win64

**Comment by BadgerCode** [comment] 2021-01-02 19:21
Cheers. I'll try it on my Linux server

**Comment by BadgerCode** [comment] 2021-01-03 15:11
I've tested this on the following setup:
* Client - Windows 10 64-bit
* Game Version - x86-64 - Chromium + 64-bit binaries (2020.12.11)
* Server - Ubuntu 16.04.7 LTS 64-bit
* Database - SQLite

I was unable to reproduce the issue 🙁

<br>

These are the lines that set up each player's name & role for a round in the damage logs:
https://github.com/BadgerCode/tttdamagelogs/blob/4a0ca3f9fed53603556760ab59ef45f7be4a135a/lua/damagelogs/server/init.lua#L88-L96

They run when the round begins (`TTTBeginRound`) and when the player first spawns.

I'm not sure what's causing the addon to lose your player name.

**Comment by Yogpod** [comment] 2021-01-03 21:48
Looks like #22 fixed it

**Comment by BadgerCode** [comment] 2021-01-03 23:15
Ah great. That's good to hear!

I will release that with the next update.
If you want to download it now, you can get it on the next-version branch

**Closed** 2021-01-03 23:15 UTC
Labels: requires-investigation
